### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bepolymathe** [petervelosy/freeplane-zotero#5] opened 2023-01-13 10:23 UTC
Hi, 

Thanks for this project. I’am searching a better integration for Zotero and Freeplane... espacially with Zotero 6 and its annotations system. 
Could you allow us to have an addon file as realease for those not easy make compilation ?
Thanks ;-)

**Comment by petervelosy** [comment] 2023-01-13 22:43
Hi, thanks for your interest in the project!

I've created a compiled release myself, you can download it from the main Readme page under "How to install?". You are right that the link could be exposed better and it would also be useful to add it as a release at GitHub to make our lives easier :-)

I created this project to cover my basic everyday needs of creating mindmaps around research topics of interest with bibliography links. I am very grateful for bug reports or feature suggestions, and you are also welcome to comtribute to the source code.

**Comment by bepolymathe** [comment] 2023-01-14 05:28
Hi @petervelosy 

Thank you for your answer. It’s a great project that I can’t wait to test.
 Personally I have an error message at the installation which mentions a freeplane version problem (I am currently with version 1.11.x).
 
Even if I try to change by hand the version number in the header of the .mm file, the software cannot start installing the addon.

**Comment by petervelosy** [comment] 2023-01-21 22:11
Hi @bepolymathe !

I have an important exam early next week but after I am done with that, I'll look into this issue and also into how the addon plays together with the latest Freeplane and Zotero versions.

Peter

**Comment by bepolymathe** [comment] 2023-01-22 05:52
Thanks ! And good luck for exam 😉

**Comment by petervelosy** [comment] 2023-01-25 01:38
So, after a successful exam I have just installed the compiled version 0.1 (from the download link in the README) on Freeplane 1.11.1 under Debian Sid. For me it worked flawlessly. To investigate this further, could you please
- Describe the exact steps you took when trying to install the plugin
- Describe what OS version you are using
- Attach a screenshot of the error
- Attach the log file of your Freeplane session (Freeplane > Tools > Open User Directory > logs > "log.0")

Thanks!

**Comment by bepolymathe** [comment] 2023-01-25 04:38
Hi @petervelosy 

> after a successful exam

Great ! 

> For me it worked flawlessly.

For me it’a a bit more complex. 

I’am working with 1.11.1 on Fedora Linux and Windows. For now, i’am testing it with Fedora 37 (workstation). 

![image](https://user-images.githubusercontent.com/29939805/214480288-170d6987-ab0f-4fca-9267-7ea8a4e08a43.png)

1. I download the `freeplane-zotero-current.mm` file. 
2. Try to install with the addon installation tool in FP
3. Get this error message. 

![image](https://user-images.githubusercontent.com/29939805/214480541-7e2ed5ce-5211-4152-b733-aa1a50f96e9b.png)

4. Logs

```
STDOUT: janv. 25, 2023 5:34:42 AM org.freeplane.core.util.LogUtils info
INFOS: freeplane_version = 1.11.1 alpha; freeplane_xml_version = freeplane 1.11.1
git revision = f6afb0711da8de55e77b8e876ee47f9c8b729ab7 Dimitry Polivaev 2023-01-15T19:54:19Z
java_version = 17.0.5; os_name = Linux; os_version = 6.1.5-200.fc37.x86_64
STDOUT: Framework launched
STDOUT: janv. 25, 2023 5:34:45 AM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: janv. 25, 2023 5:34:45 AM org.freeplane.core.util.LogUtils info
INFOS: extending script's classpath by [/home/bepolymathe/.config/freeplane/1.11.x/compiledscripts, /home/bepolymathe/.config/freeplane/1.11.x/addons/bookmarks/lib/bookmarks.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/MarkdownHelper.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/jsoup-1.10.2.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/markdownHelper/lib/markedj-1.0.16.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/mapSavingOptions/lib/MapSavingOptions.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/jumper/lib/jumper.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/mapDriveInator/lib/MapDriveInator.jar, /home/bepolymathe/.config/freeplane/1.11.x/addons/menuOMatic/lib/Menu-o-Matic.jar, /home/bepolymathe/.config/freeplane/1.11.x/lib]
STDOUT: janv. 25, 2023 5:34:45 AM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: janv. 25, 2023 5:34:46 AM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: janv. 25, 2023 5:34:46 AM org.freeplane.core.util.LogUtils info
INFOS: looking for scripts with the following endings: [groovy]
STDOUT: janv. 25, 2023 5:34:46 AM org.freeplane.core.util.LogUtils info
INFOS: looking for scripts with the following endings: [groovy]
STDOUT: janv. 25, 2023 5:34:47 AM org.freeplane.core.util.LogUtils info
INFOS: requesting mode: MindMap
STDOUT: janv. 25, 2023 5:34:51 AM org.freeplane.core.util.LogUtils info
INFOS: running init script /home/bepolymathe/.config/freeplane/1.11.x/scripts/init/BookmarksMonitorIcons.groovy
STDOUT: janv. 25, 2023 5:34:52 AM org.freeplane.core.util.LogUtils info
INFOS: running init script /home/bepolymathe/.config/freeplane/1.11.x/scripts/init/AddGTDChangeListener.groovy
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:53 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: not a pattern format: 'dd/MM/y'
STDOUT: janv. 25, 2023 5:34:54 AM org.freeplane.core.util.LogUtils info
INFOS: menu items to execute: []
STDOUT: janv. 25, 2023 5:35:20 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: Could not read update url (https://www.freeplane.org/info/history/alpha/history_fr.txt) - check your internet connection.
STDOUT: janv. 25, 2023 5:35:21 AM org.freeplane.core.util.LogUtils info
INFOS: installing add-on from /home/bepolymathe/Nuage/00 - INBOX/freeplane-zotero-current.mm
STDERR: java.lang.IllegalArgumentException: Wrong number of tokens for version information: 1,8
STDERR: at org.freeplane.core.util.FreeplaneVersion.getVersion(FreeplaneVersion.java:67)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
STDERR: at installScriptAddOn.parseFreeplaneVersion(installScriptAddOn.groovy:118)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
STDERR: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
STDERR: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
STDERR: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
STDERR: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
STDERR: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:342)
STDERR: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
STDERR: at installScriptAddOn$_parseProperties_closure1.doCall(installScriptAddOn.groovy:84)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
STDERR: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
STDERR: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
STDERR: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
STDERR: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
STDERR: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
STDERR: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
STDERR: at groovy.lang.Closure.call(Closure.java:418)
STDERR: at org.codehaus.groovy.runtime.DefaultGroovyMethods.inject(DefaultGroovyMethods.java:5916)
STDERR: at org.codehaus.groovy.runtime.dgm$427.doMethodInvoke(Unknown Source)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
STDERR: at installScriptAddOn.parseProperties(installScriptAddOn.groovy:82)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
STDERR: at installScriptAddOn.parse(installScriptAddOn.groovy:422)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
STDERR: at installScriptAddOn.run(installScriptAddOn.groovy:518)
STDERR: at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:114)
STDERR: at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
STDERR: at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:113)
STDERR: at org.freeplane.plugin.script.addons.AddOnInstallerPanel$1.actionPerformed(AddOnInstallerPanel.java:144)
STDERR: at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
STDERR: at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
STDERR: at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
STDERR: at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6391)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2266)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
STDERR: at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
STDERR: at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
STDERR: at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
STDERR: at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
STDERR: at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
STDERR: at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
STDERR: at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
STDERR: at java.desktop/java.awt.Component.show(Component.java:1728)
STDERR: at java.desktop/java.awt.Component.setVisible(Component.java:1675)
STDERR: at java.desktop/java.awt.Window.setVisible(Window.java:1036)
STDERR: at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
STDERR: at org.freeplane.plugin.script.addons.ManageAddOnsAction.actionPerformed(ManageAddOnsAction.java:17)
STDERR: at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
STDERR: at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
STDERR: at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
STDERR: at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
STDERR: at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
STDERR: at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6391)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2266)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
STDERR: at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
STDERR: at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDOUT: janv. 25, 2023 5:35:26 AM org.freeplane.core.util.LogUtils warn
AVERTISSEMENT: installation failure
java.lang.Exception: Erreur de structure dans la carte : Erreur de format pour freeplaneVersionFrom
(valeur erronnée : 1,8)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn.mapStructureAssert(installScriptAddOn.groovy:71)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn.parseFreeplaneVersion(installScriptAddOn.groovy:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:342)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn$_parseProperties_closure1.doCall(installScriptAddOn.groovy:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.inject(DefaultGroovyMethods.java:5916)
	at org.codehaus.groovy.runtime.dgm$427.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn.parseProperties(installScriptAddOn.groovy:82)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn.parse(installScriptAddOn.groovy:422)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at installScriptAddOn.run(installScriptAddOn.groovy:518)
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:114)
	at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
	at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:113)
	at org.freeplane.plugin.script.addons.AddOnInstallerPanel$1.actionPerformed(AddOnInstallerPanel.java:144)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at org.freeplane.plugin.script.addons.ManageAddOnsAction.actionPerformed(ManageAddOnsAction.java:17)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDOUT: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDOUT: janv. 25, 2023 5:36:01 AM org.freeplane.core.util.LogUtils info
INFOS: execute [xdg-open, https://www.freeplane.org/bugs]
STDOUT: janv. 25, 2023 5:36:12 AM org.freeplane.core.util.LogUtils info
INFOS: execute [xdg-open, file:/home/bepolymathe/Nuage/05%20-%20JOURNAL/]
STDOUT: janv. 25, 2023 5:36:20 AM org.freeplane.core.util.LogUtils info
INFOS: execute [xdg-open, file:/home/bepolymathe/.config/freeplane/1.11.x/]
```

**Comment by bepolymathe** [comment] 2023-01-25 04:42
Are you sure you pushed the new addon file on github I feel like I'm testing the same file as last time 🤔

**Comment by petervelosy** [comment] 2023-01-25 10:16
I did not upload a new version of the compiled addon file because the current one worked on my end with Freeplane 1.11.1 without any modifications.

I have managed to reproduce the issue by setting Freeplane to French. It seems to be a locale-dependent issue having to do with the fact that French uses a decimal comma, while English uses a decimal point.

Interestingly, the problem does not affect every plugin (e.g. I could install Developer Tools with Freeplane set to French)

As a workaround, you can set Freeplane to English. Nevertheless, we need to investigate whether e.g. the format of the freeplaneVersionFrom field differs between freeplane-zotero and Developer Tools.

**Comment by bepolymathe** [comment] 2023-01-25 11:01
Thanks for reply and clarifications...
Change the language for english change nothing for me... 

![image](https://user-images.githubusercontent.com/29939805/214546555-d08c4981-d012-40b9-ad53-641c8b97c6f4.png)

**Comment by petervelosy** [comment] 2023-01-25 19:53
I've pushed a fix that resolved the problem on my end: I've changed the value of freeplaneVersionFrom from "1.8" to "v1.8", so that it does not get interpreted as a number. The Development Tools plugin has it in the same way, so I still think the culprit is the decimal separator (maybe in your case it conflicts with the OS locale setting). 

I've also uploaded this fixed version to GitHub as a Release. Please download it from https://github.com/petervelosy/freeplane-zotero/releases/ and let me know if it fixed your issue.

**Comment by bepolymathe** [comment] 2023-01-25 20:56
OK that's great, it works 👍
I'll test it tomarrow for discussion 😃

**Comment by petervelosy** [comment] 2023-01-25 23:13
I'm glad to hear that! I am closing this issue, feel free to open new ones once you have suggestions or bug reports.

**Closed as completed by petervelosy** 2023-01-25 23:13 UTC
